"""Shared constants for field normalization, quality checks, and observability."""

MICROCHIP_MIN_DIGITS: int = 9
MICROCHIP_MAX_DIGITS: int = 15

WEIGHT_MIN_KG: float = 0.5
WEIGHT_MAX_KG: float = 120.0

MAX_VALUE_LENGTH: int = 80
PET_NAME_MIN_LENGTH: int = 1
CLINIC_NAME_MIN_LENGTH: int = 2
CLINIC_ADDRESS_MIN_LENGTH: int = 10
OWNER_ADDRESS_MAX_LENGTH: int = 120

MAX_PET_AGE_YEARS: int = 40
DAYS_PER_YEAR: float = 365.25

PHONE_DIGIT_COUNT: int = 9

QUALITY_SCORE_THRESHOLD: float = 0.60

# Quality gate: prerequisite thresholds
QUALITY_MIN_TEXT_LENGTH: int = 20
QUALITY_MIN_WORD_TOKENS: int = 3

# Quality gate: human-readability thresholds
HUMAN_READABLE_MIN_LENGTH: int = 3
HUMAN_READABLE_PRINTABLE_RATIO: float = 0.9
HUMAN_READABLE_LETTER_RATIO: float = 0.35
HUMAN_READABLE_STRANGE_CHAR_RATIO: float = 0.15

# Quality gate: scoring rule thresholds
VOWEL_RATIO_MIN: float = 0.30
PUNCTUATION_RATIO_MAX: float = 0.25
WHITESPACE_RATIO_MIN: float = 0.10
LINEBREAK_RATIO_MIN: float = 0.0005
LINEBREAK_MIN_TEXT_LENGTH: int = 800
LONG_TOKEN_MIN_LENGTH: int = 12
LONG_TOKEN_RATIO_MAX: float = 0.20
LONG_TOKEN_MIN_SAMPLE: int = 80
SINGLE_LETTER_RATIO_MAX: float = 0.045
SINGLE_LETTER_MIN_SAMPLE: int = 120
ALL_CAPS_RATIO_MAX: float = 0.80
ALL_CAPS_MAX_SAMPLE: int = 250
