module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        appBg: "var(--app-bg)",
        canvas: "var(--canvas-bg)",
        cardBg: "var(--card-bg)",
        frame: "var(--app-frame)",
        page: "var(--app-bg)",
        surface: "var(--color-surface)",
        surfaceMuted: "var(--color-surface-muted)",
        text: "var(--color-text)",
        ink: "var(--color-text)",
        textTitle: "var(--text-title)",
        textBody: "var(--text-body)",
        textMuted: "var(--text-muted)",
        textSecondary: "var(--color-text-secondary)",
        muted: "var(--color-text-muted)",
        border: "var(--color-border)",
        borderSubtle: "var(--color-border-subtle)",
        accent: "var(--color-accent)",
        accentSoft: "var(--color-border-subtle)",
        accentForeground: "var(--color-accent-foreground)",
        confidenceLow: "var(--confidence-low)",
        confidenceMed: "var(--confidence-med)",
        confidenceHigh: "var(--confidence-high)",
        statusSuccess: "var(--status-success)",
        statusWarn: "var(--status-warn)",
        statusError: "var(--status-error)",
        critical: "var(--status-critical)",
        missing: "var(--status-missing)",
      },
      fontFamily: {
        display: ["\"Inter\"", "system-ui", "-apple-system", "\"Segoe UI\"", "Roboto", "sans-serif"],
        body: ["\"Inter\"", "system-ui", "-apple-system", "\"Segoe UI\"", "Roboto", "sans-serif"],
      },
      spacing: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        8: "32px",
      },
      borderRadius: {
        sm: "6px",
        DEFAULT: "var(--radius-control)",
        md: "var(--radius-control)",
        lg: "var(--radius-card)",
        xl: "var(--radius-card)",
        "2xl": "var(--radius-frame)",
        "3xl": "var(--radius-frame)",
        frame: "var(--radius-frame)",
        card: "var(--radius-card)",
        control: "var(--radius-control)",
      },
      boxShadow: {
        soft: "var(--shadow-soft)",
        subtle: "var(--shadow-subtle)",
      },
    },
  },
  plugins: [],
};
